title: Quazi Marufur Rahman
description: PhD in Robotic Vision | CV & AI Team Lead @ AMAG

paginate_path: "index/page:num/"



# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highligh  ter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /home
    - title: Research
      url: /research
    - title: Industry
      url: /industry
    - title: Notes
      url: /index
    
    

social:
    github: qmaruf
    twitter: maruf_q
    email: maruf.csdu@gmail.com
    linkedin: qmaruf

# google_analytics: "UA-58263416-1"
