title: Quazi Marufur Rahman
description: PhD in Robotic Vision | CV & AI Team Lead @ AMAG

url: https://long-haul.netlify.app
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: Research
      url: /research
    - title: Academic
      url: /academic
    - title: Industry
      url: /industry
    
    

social:
    github: qmaruf
    twitter: maruf_q
    email: maruf.csdu@gmail.com
    linkedin: qmaruf

# google_analytics: "UA-58263416-1"

